[window]
opacity = 0.9
padding = {x=3, y=3}

[font]
normal = {family = 'Monofur Nerd Font', style = 'Normal'}
bold = {family = 'Monofur Nerd Font', style = 'Normal'}
italic = {family = 'Monofur Nerd Font', style = 'Normal'}
size = 9.6
offset = {x=1, y=1}

# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

# Normal Colours
[colors.normal]
black   = '#1a1a1a'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#fa8419'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#c4c5b5'

# Bright Colours
[colors.bright]
black   = '#625e4c'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#e0d561'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#f6f6ef'

